In [1]:
# EIGEN DECOMPOSITION USING PYTHON

# Matrix Reconstruction

In [2]:
# Installing Useful Packages And Libraries
from numpy import diag
from numpy import dot
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig

In [3]:
# Defining The Matrix
A = array([[9, 2, 3, 6, 8], [3, 5, 2, 9, 8], [1, 3, 6, 8, 3], [4, 6, 1, 7, 9], [6, 7, 5, 8, 2]])
print(A)

[[9 2 3 6 8]
 [3 5 2 9 8]
 [1 3 6 8 3]
 [4 6 1 7 9]
 [6 7 5 8 2]]


In [6]:
# Calculating EigenValues And EigenVectors
values, vectors = eig(A)
print("EigenValues Of Matrix A : \n",values)
print("\nEigenVectors Of Matrix A : \n",vectors)

EigenValues Of Matrix A : 
 [26.72901319+0.j          4.44698071+1.29420835j  4.44698071-1.29420835j
 -5.10405995+0.j         -1.51891465+0.j        ]

EigenVectors Of Matrix A : 
 [[-0.47979491+0.j         -0.44405489-0.31744603j -0.44405489+0.31744603j
  -0.29042463+0.j          0.11479635+0.j        ]
 [-0.46416219+0.j          0.03344355+0.15447885j  0.03344355-0.15447885j
  -0.22456642+0.j         -0.36853808+0.j        ]
 [-0.33915514+0.j          0.7916804 +0.j          0.7916804 -0.j
   0.16413789+0.j         -0.44270328+0.j        ]
 [-0.4691969 +0.j         -0.15344078+0.11617019j -0.15344078-0.11617019j
  -0.41361829+0.j          0.69527759+0.j        ]
 [-0.46816489+0.j          0.11391852-0.01691757j  0.11391852+0.01691757j
   0.81682441+0.j         -0.41425157+0.j        ]]


In [8]:
# Matrix Creation From EigenVectors
Q = vectors
print("Matrix Formed By EigenVectors : \n",Q)

Matrix Formed By EigenVectors : 
 [[-0.47979491+0.j         -0.44405489-0.31744603j -0.44405489+0.31744603j
  -0.29042463+0.j          0.11479635+0.j        ]
 [-0.46416219+0.j          0.03344355+0.15447885j  0.03344355-0.15447885j
  -0.22456642+0.j         -0.36853808+0.j        ]
 [-0.33915514+0.j          0.7916804 +0.j          0.7916804 -0.j
   0.16413789+0.j         -0.44270328+0.j        ]
 [-0.4691969 +0.j         -0.15344078+0.11617019j -0.15344078-0.11617019j
  -0.41361829+0.j          0.69527759+0.j        ]
 [-0.46816489+0.j          0.11391852-0.01691757j  0.11391852+0.01691757j
   0.81682441+0.j         -0.41425157+0.j        ]]


In [9]:
# Finding Inverse Of EigenVectors Matrix
R = inv(Q)
print("Inverse Of EigenVectors Matrix Is : \n",R)

Inverse Of EigenVectors Matrix Is : 
 [[-0.39857309-1.15697665e-16j -0.40944276+1.15697665e-16j
  -0.25195706+1.15697665e-16j -0.62005804-5.78488327e-17j
  -0.51763167-1.15697665e-16j]
 [-0.09830691+1.01653527e+00j -0.32956139-8.76129636e-01j
   0.64434537+5.58992257e-01j  0.14301118-3.88668396e-01j
  -0.18262018-1.88577350e-01j]
 [-0.09830691-1.01653527e+00j -0.32956139+8.76129636e-01j
   0.64434537-5.58992257e-01j  0.14301118+3.88668396e-01j
  -0.18262018+1.88577350e-01j]
 [-0.32832349+8.18648494e-18j -0.67139811-2.83302200e-17j
  -0.27861168+1.21677853e-17j  0.14918397+1.14478730e-17j
   1.05446071+1.46933412e-18j]
 [-0.16798504+7.69761228e-17j -1.11395569-8.94179438e-17j
   0.13542481+7.42115178e-17j  1.04182853-2.56326451e-17j
   0.13435807-3.35669568e-18j]]


In [10]:
# Diagonal Matrix Creation From EigenValues
L = diag(values)
print("Diagonal Matrix Formed By EigenValues : \n",L)

Diagonal Matrix Formed By EigenValues : 
 [[26.72901319+0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          4.44698071+1.29420835j  0.        +0.j
   0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          4.44698071-1.29420835j
   0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
  -5.10405995+0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j         -1.51891465+0.j        ]]


In [11]:
# Reconstructing Original Matrix A
B = Q.dot(L).dot(R)
print(B)

[[9.+1.55302542e-15j 2.-1.35867135e-15j 3.-1.32717073e-15j
  6.+6.32061816e-16j 8.+1.33503098e-15j]
 [3.+1.31535157e-15j 5.-1.58132738e-15j 2.-1.38780124e-15j
  9.+7.48173511e-16j 8.+1.48472844e-15j]
 [1.+1.37717018e-15j 3.-9.24571395e-16j 6.-1.29255949e-15j
  8.+4.17262409e-16j 3.+1.10673492e-15j]
 [4.+1.15723611e-15j 6.-1.40866741e-15j 1.-1.38495218e-15j
  7.+8.28393893e-16j 9.+1.46381458e-15j]
 [6.+1.56861615e-15j 7.-1.38144074e-15j 5.-1.50283521e-15j
  8.+6.85544589e-16j 2.+1.46280760e-15j]]


In [5]:
# CHOLESKY DECOMPOSITION
import numpy as np
import scipy
import scipy.linalg
a = np.array(([[19,-12,-12,-19],[-12,27,1,-4],[-12,1,11,14],[-19,4,14,51]]), dtype=np.int32)
print("The Matrix Formed Is :")
print(a)
L = np.linalg.cholesky(a)
print("\nLower-Trianglular Matrix L In Cholesky Decomposition Is :")
print(L)
U = scipy.linalg.cholesky(a,lower=False)
print("\nUpper-Trianglular Matrix U In Cholesky Decomposition Is :")
print(U)

The Matrix Formed Is :
[[ 19 -12 -12 -19]
 [-12  27   1  -4]
 [-12   1  11  14]
 [-19   4  14  51]]

Lower-Trianglular Matrix L In Cholesky Decomposition Is :
[[ 4.35889894  0.          0.          0.        ]
 [-2.75298881  4.40693234  0.          0.        ]
 [-2.75298881 -1.49286326  1.09197616  0.        ]
 [-4.35889894 -1.81532172 -0.65022217  5.31806527]]

Upper-Trianglular Matrix U In Cholesky Decomposition Is :
[[ 4.35889894 -2.75298881 -2.75298881 -4.35889894]
 [ 0.          4.40693234 -1.49286326 -3.63064344]
 [ 0.          0.          1.09197616 -3.13198616]
 [ 0.          0.          0.          3.00151477]]


In [1]:
# GAUSS JORDAN METHOD
import numpy as np
import sys
n = int(input('Enter Number Of Variables : '))
a = np.zeros((n,n+1))
x = np.zeros(n)
print('Enter Augmented Matrix Coefficients:')
for i in range(n):
    for j in range(n+1):
        a[i][j] = float(input( 'a['+str(i)+']['+ str(j)+']='))
for i in range(n):
    if a[i][i] == 0.0:
        sys.exit('Cannot Divide By Zero')
    for j in range(n):
        if i != j:
            ratio = a[j][i]/a[i][i]

            for k in range(n+1):
                a[j][k] = a[j][k] - ratio * a[i][k]
for i in range(n):
    x[i] = a[i][n]/a[i][i]
print('\nSolution : ')
for i in range(n):
    print('X%d = %0.2f' %(i,x[i]), end = '\t')

Enter Number Of Variables : 3
Enter Augmented Matrix Coefficients:
a[0][0]=3
a[0][1]=5
a[0][2]=-2
a[0][3]=10
a[1][0]=1
a[1][1]=4
a[1][2]=1
a[1][3]=7
a[2][0]=9
a[2][1]=0
a[2][2]=2
a[2][3]=1

Solution : 
X0 = 0.18	X1 = 1.78	X2 = -0.29	