In [5]:
# Singular-Value Decomposition
from numpy import array
from scipy.linalg import svd
# Defining Matrix
A = array([[5, 1, 7, 6], [3, 8, 5, 1], [7, 4, 5, 6], [2, 5, 4, 1]])
print(A,"\n")
# Evaluating SVD
U, s, VT = svd(A)
print(U,"\n")
print(s,"\n")
print(VT)

[[5 1 7 6]
 [3 8 5 1]
 [7 4 5 6]
 [2 5 4 1]] 

[[-0.53567222  0.54915035  0.62215907 -0.15622819]
 [-0.48019039 -0.68445996  0.05361093 -0.54594653]
 [-0.60515718  0.27740491 -0.7377526   0.11203754]
 [-0.34096516 -0.39114572  0.25644699  0.81546473]] 

[1.79952589e+01 7.20388081e+00 2.50493913e+00 6.15897159e-03] 

[[-0.50218577 -0.47249389 -0.58572673 -0.42600843]
 [ 0.25707182 -0.8013234   0.0338976   0.53911579]
 [-0.5508102  -0.24660435  0.78253126 -0.15309881]
 [-0.61508671  0.27169214 -0.20837461  0.71023358]]


In [6]:
# Reconstructing SVD
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd
# Defining The Same Matrix As above
A = array([[5, 1, 7, 6], [3, 8, 5, 1], [7, 4, 5, 6], [2, 5, 4, 1]])
print(A,"\n")
# Evaluating SVD
U, s, VT = svd(A)
# Creating m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
# Reconstructing matrix
B = U.dot(Sigma.dot(VT))
print(B)

[[5 1 7 6]
 [3 8 5 1]
 [7 4 5 6]
 [2 5 4 1]] 

[[5. 1. 7. 6.]
 [3. 8. 5. 1.]
 [7. 4. 5. 6.]
 [2. 5. 4. 1.]]
